POST http://localhost:8000/api/properties/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
    "property_id":"d02131c2-8230-49fa-bb37-b12797df0009",
    "owner_id":"1f8be170-f711-64d4-a807-6a7d91c80bc9",
    "address":"1618 Sullivan Ave #385",
    "city":"Daly City",
    "state":"CA",
    "zip":70115,
    "description":"fabulous",
    "rent":1000.50,
    "furnitures":[
        {
            "furniture_id":"53cd8f8f-0bed-414d-b29f-e99d41489b1c",
            "description":"Sofa",
            "condition":10,
            "inservice_date":"2022-12-01",
            "expected_life":48
        },
        {
            "furniture_id":"53cd8f8f-0bed-414d-b29f-e99d41489b1d",
            "description":"Sofa",
            "condition":10,
            "inservice_date":"2022-12-01",
            "expected_life":48
        },
        {
            "furniture_id":"53cd8f8f-0bed-414d-b29f-e99d41489b1e",
            "description":"Sofa",
            "condition":10,
            "inservice_date":"2022-12-01",
            "expected_life":48
        }
    ],
    "inspections":[
        {
            "inspection_id":"faebe42c-ad03-43d7-bd71-15f0a1cd9735",
            "inspector_id":"1f8be170-f711-64d4-a807-6a7d91c80bc9",
            "inspection_date":"2022-11-09",
            "findings":"none",
            "inspection_items":[
                {
                    "inspection_item_id":"b586c097-13d3-491f-b084-577ca5afe1ec",
                    "description":"foo",
                    "details": [
                        {
                            "detail_id": "8c9e30f0-56f4-4dff-94f0-7ca886c8d5dd",
                            "description": "abc"
                        },
                        {
                            "detail_id": "8c9e30f0-56f4-4dff-94f0-7ca886c8d5de",
                            "description": "xyz"
                        }
                    ]
                },
                {
                    "inspection_item_id":"b586c097-13d3-491f-b084-577ca5afe1ed",
                    "description":"bar"
                },
                {
                    "inspection_item_id":"b586c097-13d3-491f-b084-577ca5afe1ee",
                    "description":"baz"
                }
            ]
        }
    ],
    "vehicles":[
        {
            "vehicle_id":"6f7aed5d-500a-48d1-933b-b51d88551997",
            "make":"Chevrolet",
            "model":"Express",
            "year":2003,
            "description":"Van",
            "last_maintenance":"2023-02-10"
        },
        {
            "vehicle_id":"6f7aed5d-500a-48d1-933b-b51d88551998",
            "make":"Chevrolet",
            "model":"Express",
            "year":2004,
            "description":"Van",
            "last_maintenance":"2023-02-10"
        },
        {
            "vehicle_id":"6f7aed5d-500a-48d1-933b-b51d88551999",
            "make":"Chevrolet",
            "model":"Express",
            "year":2005,
            "description":"Van",
            "last_maintenance":"2023-02-10"
        }
    ]
}
