# Create a user. Try this again to get a Database Error
POST http://localhost:8000/api/users/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
    "user_id": "1f8be170-f711-64d4-a807-6a7d91c80bc9",
    "email": "javin@tdeamengixney.org",
    "phone": "415-264-0616",
    "dob": "1980-10-15",
    "address": "1618 Sullivan Ave #385",
    "city": "Daly City",
    "state": "CA",
    "zip": 70115
}

# Create another user.
POST http://localhost:8000/api/users/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
    "user_id": "1c8be170-f711-64d4-a807-6a7d91c80bc9",
    "email": "inspector@gadget.org",
    "phone": "415-264-0616",
    "dob": "1980-10-15",
    "address": "1618 Sullivan Ave #385",
    "city": "Daly City",
    "state": "CA",
    "zip": 70115
}

# Attempt to create a user with bad data

POST http://localhost:8000/api/users/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
    "user_id": "6c8be170-f711-44d4-b807-6a7d91c80bc9",
    "email": "javin@teamengine.org",
    "phone": "415-264-0616",
    "dob": "1980-10-15",
    "address": "1618 Sullivan Ave #385",
    "city": "Daly City",
    "state": "CA",
    "zip": "BAD DATA"
}

# Get the users
GET http://localhost:8000/api/users/
Accept: application/json;charset=utf-8

# Post a property by itself
POST http://localhost:8000/api/properties/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
"property":
    {
        "property_id": "d02131c2-8230-49fa-bb37-b12797df0009",
        "owner_id": "1f8be170-f711-64d4-a807-6a7d91c80bc9",
        "address": "1618 Sullivan Ave #385",
        "city": "Daly City",
        "state": "CA",
        "zip": 70115,
        "description": "fabulous",
        "rent": 1000.50
    }
}

# Post a property with an inspection
# (an inspection is required before property is posted)
POST http://localhost:8000/api/properties/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
    "property": {
        "property_id": "d02131c2-8230-49fa-bb37-b12797df0009",
        "owner_id": "1f8be170-f711-64d4-a807-6a7d91c80bc9",
        "address": "1618 Sullivan Ave #385",
        "city": "Daly City",
        "state": "CA",
        "zip": 70115,
        "description": "fabulous",
        "rent": 1000.50,
        "inspection": {
            "inspection_id": "faebe42c-ad03-43d7-bd71-15f0a1cd9735",
            "inspector_id":  "1f8be170-f711-64d4-a807-6a7d91c80bc9",
            "inspection_date": "2022-11-09",
            "findings": "none"
        }
    }
}

# Post a property with some furniture
POST http://localhost:8000/api/properties/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
"property":
    {
        "property_id": "d02131c2-8230-49fa-bb37-b12797df0009",
        "owner_id": "1f8be170-f711-64d4-a807-6a7d91c80bc9",
        "address": "1618 Sullivan Ave #385",
        "city": "Daly City",
        "state": "CA",
        "zip": 70115,
        "description": "fabulous",
        "rent": 1000.50,
        "furniture": [
            {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1c",
                "description": "Sofa",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            },
            {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1d",
                "description": "Chairs",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            },
            {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1e",
                "description": "Desk",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            }
        ],
        "inspection": {
            "inspection_id": "faebe42c-ad03-43d7-bd71-15f0a1cd9735",
            "inspector_id":  "1f8be170-f711-64d4-a807-6a7d91c80bc9",
            "inspection_date": "2022-11-09",
            "findings": "none"
        }
    }
}
# Post a property with some furnitures and vehicles (many:many)
POST http://localhost:8000/api/properties/
Content-Type: application/json
Accept: application/json;charset=utf-8

{
"property":
    {
        "property_id": "d02131c2-8230-49fa-bb37-b12797df0009",
        "owner_id": "1f8be170-f711-64d4-a807-6a7d91c80bc9",
        "address": "1618 Sullivan Ave #385",
        "city": "Daly City",
        "state": "CA",
        "zip": 70115,
        "description": "fabulous",
        "rent": 1000.50,
        "furniture": {
            "0": {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1c",
                "description": "Sofa",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            },
            "1": {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1d",
                "description": "Table",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            },
            "2": {
                "furniture_id": "53cd8f8f-0bed-414d-b29f-e99d41489b1e",
                "description": "Chairs",
                "condition": 10,
                "inservice_date": "2022-12-01",
                "expected_life": 48
            }
        },
        "inspection": {
            "inspection_id": "faebe42c-ad03-43d7-bd71-15f0a1cd9735",
            "inspector_id":  "1f8be170-f711-64d4-a807-6a7d91c80bc9",
            "inspection_date": "2022-11-09",
            "findings": "none",
            "inspection_items": {
                "0": {
                    "inspection_item": {
                        "inspection_item_id": "b586c097-13d3-491f-b084-577ca5afe1ec",
                        "description": "foo"
                    }
                },
                "1": {
                    "inspection_item": {
                        "inspection_item_id": "b586c097-13d3-491f-b084-577ca5afe1ed",
                        "description": "bar"
                    }
                },
                "2": {
                    "inspection_item": {
                        "inspection_item_id": "b586c097-13d3-491f-b084-577ca5afe1ee",
                        "description": "baz"
                    }
                }
            }
        },
        "vehicles": {
            "0": {
                "vehicle": {
                    "vehicle_id": "6f7aed5d-500a-48d1-933b-b51d88551997",
                    "make": "Chevrolet",
                    "model": "Express",
                    "year": 2003,
                    "description": "Van",
                    "last_maintenance": "2023-02-10"
                }
            },
            "1": {
                "vehicle": {
                    "vehicle_id": "6f7aed5d-500a-48d1-933b-b51d88551998",
                    "make": "Chevrolet",
                    "model": "Express",
                    "year": 2004,
                    "description": "Van",
                    "last_maintenance": "2023-02-10"
                }
            },
            "2": {
                "vehicle": {
                    "vehicle_id": "6f7aed5d-500a-48d1-933b-b51d88551999",
                    "make": "Chevrolet",
                    "model": "Express",
                    "year": 2005,
                    "description": "Van",
                    "last_maintenance": "2023-02-10"
                }
            }
        }
    }
}
# Get the properties
GET http://localhost:8000/api/properties/
Accept: application/json;charset=utf-8
