# Generated by Django 4.1.7 on 2023-03-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
    ]
