# Generated by Django 4.1.7 on 2023-03-12 00:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "property_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("zip", models.CharField(blank=True, max_length=12)),
                ("description", models.TextField(blank=True)),
                ("rent", models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(blank=True, max_length=17)),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("zip", models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=64, null=True)),
                ("model", models.CharField(blank=True, max_length=64, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("properties", models.ManyToManyField(to="propertymanager.property")),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="propertymanager.user"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="vehicles",
            field=models.ManyToManyField(to="propertymanager.vehicle"),
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "inspection_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("findings", models.TextField()),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="propertymanager.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="propertymanager.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "furniture_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("condition", models.IntegerField(blank=True, null=True)),
                ("inservice_date", models.DateField(blank=True, null=True)),
                ("expected_life", models.IntegerField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="propertymanager.property",
                    ),
                ),
            ],
        ),
    ]
