
delete from propertymanager_detail;
delete from propertymanager_property_vehicles;
delete from propertymanager_vehicle_properties;
delete from propertymanager_vehicle;
delete from propertymanager_furniture;
delete from propertymanager_inspectionitem;
delete from propertymanager_inspection;
delete from propertymanager_property;
